services:
  client:
    container_name: dsa-visualization-client
    build:
      context: .
      dockerfile: Dockerfile
    image: dsa-visualization:latest
    ports:
      - "5173:80"   # Browser accesses port 5173 â†’ maps to Nginx 80
    restart: unless-stopped