apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsa-visualization
  namespace: 2401003
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsa-visualization
  template:
    metadata:
      labels:
        app: dsa-visualization
    spec:
      containers:
        - name: dsa-visualization
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401003-project/dsa-visualization:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"