apiVersion: v1
kind: Service
metadata:
  name: dsa-visualization-service
  namespace: 2401003
spec:
  selector:
    app: dsa-visualization
  ports:
    - port: 80        # service port
      targetPort: 80  # container port
  type: NodePort